modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="venture"
version="1.0.0"
displayName="Venture"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/venture/update.json"
displayURL="http://mrcrayfish.com/mods?id=venture"
logoFile="venture.png"
credits="@Capptianm on Twitter for the mod idea"
authors="MrCrayfish"
description="A mod that builds upon adventuring in Minecraft"

[[dependencies.venture]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.venture]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1, 1.17)"
    ordering="NONE"
    side="BOTH"